import { Fragment } from "react";
import { getKeywordProjects, getPostsFiles } from "/helpers/posts-utils";
import PostGrid from "/components/posts/posts-grid/grid";

function KeywordsPage(props) {
  return (
    <Fragment>
      <h1 style={{ "text-transform": "capitalize" }}>{props.slug} Projects</h1>
      <PostGrid projects={props.projects} />
      <footer>
        <i>
          Credits: Images were generated by both Adobe Firefly text to image
          generative AI and Microsoft Bing Image Creator
        </i>
      </footer>
      <div style={{ height: "100px" }} />
    </Fragment>
  );
}

export function getStaticProps(context) {
  const { params } = context;
  const { slug } = params;
  const projectsArray = getKeywordProjects(slug);

  // Redirect to 404 if there are no projects with the given keyword.
  if (projectsArray.length == 0) {
    return {
      notFound: true,
    };
  }

  // Return relevant projects
  return {
    props: {
      slug: slug,
      projects: projectsArray,
    },
  };
}

export function getStaticPaths() {
  let postFilenames = [];
  for (const field of ("cs", "ds", "ee")) {
    const postFilenames = getPostsFiles("cs");

    const slugs = postFilenames.map((fileName) =>
      fileName.replace(/\.md$/, ""),
    );

    for (const slug of slugs) {
      postFilenames.push(slug);
    }
  }

  const slugs = postFilenames.map((fileName) => fileName.replace(/\.md$/, ""));

  return {
    paths: slugs.map((slug) => ({ params: { slug: slug } })),
    fallback: "blocking",
  };
}

export default KeywordsPage;
