import { Fragment } from "react";
import { getAllPosts } from "/helpers/posts-utils";
import PostGrid from "/components/posts/posts-grid/grid";

function DataSciencePage(props) {
  return (
    <Fragment>
      <h1>Data Science Projects</h1>
      <PostGrid projects={props.projects} />
      <footer>
        <i>
          Credits: Images were generated by both Adobe Firefly text to image
          generative AI and Microsoft Bing Image Creator
        </i>
      </footer>
      <div style={{ height: "100px" }} />
    </Fragment>
  );
}

export function getStaticProps() {
  const dsProjects = getAllPosts("ds");
  return {
    props: {
      projects: dsProjects,
    },
  };
}

export default DataSciencePage;
