import Styles from "./intro.module.css";
import GithubCorner from "../github-corner/github-corner";
import PostGrid from "../posts/posts-grid/grid";

function Intro(props) {
  return (
    <div className={Styles.introSection}>
      <div className={Styles.sectionSpacer} />

      <GithubCorner href="https://github.com/avivfaraj/portfolio" />
      <div className={Styles.introContent}>
        <h2 className={Styles.sectionTitle}> Welcome </h2>
        <p style={{ fontSize: "20px" }}>
          I am a Data Scientist at USAA Federal Savings Bank. I Graduated from
          Drexel University with Master of Science in Data Science with 4.0 GPA.
          I also have a dual Bachelor degree in Physics & Electrical
          Engineering, and in this portfolio I aim to showcase a wide variety of
          projects in Data Science, Computer Science, Physics and Engineering.
        </p>
      </div>
      <div className={Styles.contentSpacer} />
      <h2 className={Styles.sectionTitle}>Featured Posts</h2>
      <div className={Styles.featuredPosts}>
        <PostGrid projects={props.projects} />
      </div>
      <div className={Styles.contentSpacer} />
      <footer className={Styles.introFooter}>
        <i>
          Credits: Images were generated by both Adobe Firefly text to image
          generative AI and Microsoft Bing Image Creator
        </i>
      </footer>
      <div className={Styles.contentSpacer} />
    </div>
  );
}

export default Intro;
