import { Fragment } from "react";
import { getAllPosts } from "/helpers/posts-utils";
import PostGrid from "/components/posts/posts-grid/grid";
import Styles from "/styles/index.module.css";

function DataSciencePage(props) {
    return (
        <Fragment>
            <h1 className={Styles.h1}>Engineering Projects</h1>
            <PostGrid projects={props.projects} />
            <footer>
                <i>
                    Credits: Images were generated by both Adobe Firefly text to
                    image generative AI and Microsoft Bing Image Creator
                </i>
            </footer>
            <div style={{ height: "100px" }} />
        </Fragment>
    );
}

export function getStaticProps() {
    const eeProjects = getAllPosts("ee");
    return {
        props: {
            projects: eeProjects,
        },
    };
}

export default DataSciencePage;
